### ISSUE TITLE
集成 Bundlr

### ISSUE THREAD

**Issue by fewwwww** [WeLightProject/function_server_based_on_arweave#8]
集成 Bundlr, 实现通过除 Arweave 网络外钱包付费的文件上传. 
对于 Bundlr 组件, 除上传文件外需要支持文字粘贴, 并允许自行填写tags字段, 默认为 application/***. *** 是相应的编程语言: 如 elixir/rust/JavaScript.

**Comment by leeduckgo** [comment]
好👍
